### ISSUE TITLE
Add warning message when user tries to split pane on the Preview tab

### ISSUE THREAD

**Issue by jerone** [Glavin001/atom-preview#107]
[Enter steps to reproduce below:]
1. Make sure [Preview](https://github.com/Glavin001/atom-preview/) is installed
2. Open Preview by running command `preview:toggle`
3. A Preview pane will open, focus this pane
4. Split pane (any direction will do)
5. See error appear:

**Atom Version**: 1.0.2
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:602

TypeError: undefined is not a function
  at Pane.module.exports.Pane.copyActiveItem (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:602:168)
  at Pane.module.exports.Pane.split (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:685:32)
  at Pane.module.exports.Pane.splitUp (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:672:19)
  at atom-pane.atom.commands.add.pane:split-up (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane-element.js:275:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
  at CommandRegistry.__bind [as handleCommandEvent] (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\atom.asar\renderer\api\lib\remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.jQuery.event.add.handler (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.jQuery.event.add.elemData.handle (C:\Users\jerone\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```
### Commands

```
     -2:04.2.0 application:new-file (atom-pane.pane.active)
  4x -1:45.6.0 preview:toggle (div.settings-view.pane-item)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "tool-bar-main",
      "toolbar-basic",
      "enhanced-tabs"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "editor": {
    "fontSize": 11,
    "invisibles": {},
    "showInvisibles": true
  }
}
```
### Installed Packages

``` coffee
# User
about, v1.0.1
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.9
atom-notifier, v0.3.3
atom-yeoman, v0.3.11
color-picker, v2.0.11
editorconfig, v1.0.1
file-icons, v1.5.8
flex-tool-bar, v0.4.4
foldername-tabs, v0.1.4
gutter-shadow, v0.5.0
indentation-indicator, v0.6.0
json-schema, v0.1.10
language-jade, v0.5.1
language-sln, v0.1.0
linter, v1.2.4
linter-coffeelint, v1.0.0
markdown-scroll-sync, v0.4.0
menu-manager, v0.4.2
minimap, v4.12.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.7
minimap-selection, v4.3.0
new-tab, v0.3.0
open-recent, v2.3.0
preview, v0.16.3
project-view, v0.1.2
soft-wrap-indicator, v0.7.0
spell-check, v0.59.0
symbols-tree-view, v0.9.3
tool-bar, v0.1.8
travis-ci-status, v0.16.0
useful-context-menu, v0.2.1

# Dev
flex-tool-bar, v0.4.4
new-tab, v0.3.0
timecop, v0.31.0
tool-bar, v0.1.8
tree-view, v0.179.0
```

**Comment by jerone** [comment]
Ref: https://github.com/atom/atom/issues/7987

**Comment by Glavin001** [comment]
To confirm, you are splitting the Preview tab pane? I suppose this would be expected to error, as this should not be done. However I would at least like this to fail gracefully or show a warning message to the user or something.

**Comment by jerone** [comment]
[**@Glavin001**](https://github.com/Glavin001) commented on [27 jul. 2015 05:56 CEST](https://github.com/Glavin001/atom-preview/issues/107#issuecomment-125078999 "2015-07-27T03:56:46Z - Replied by Github Comment Enhancer"):
> To confirm, you are splitting the Preview tab pane? I suppose this would be expected to error, as this should not be done. However I would at least like this to fail gracefully or show a warning message to the user or something.

Yeah splitting the Preview tab pane. 

A nice warning message would be great if multiple Previews are not possible.

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
