### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by Hollowbean** [Glavin001/atom-preview#93]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.3
**Thrown From**: [preview](https://github.com/Glavin001/atom-preview) package, v0.13.7

### Stack Trace

Uncaught TypeError: Converting circular structure to JSON

```
At /Users/stevenbuelow/.atom/packages/preview/node_modules/analytics-node/node_modules/superagent/lib/node/index.js:801

TypeError: Converting circular structure to JSON
  at stringify (native)
  at Request.end (/Users/stevenbuelow/.atom/packages/preview/node_modules/analytics-node/node_modules/superagent/lib/node/index.js:801:29)
  at attemptRetry (/Users/stevenbuelow/.atom/packages/preview/node_modules/analytics-node/node_modules/superagent-retry/lib/index.js:38:21)
  at Request.end (/Users/stevenbuelow/.atom/packages/preview/node_modules/analytics-node/node_modules/superagent-retry/lib/index.js:48:12)
  at Analytics.flush (/Users/stevenbuelow/.atom/packages/preview/node_modules/analytics-node/lib/index.js:159:6)

```

### Commands

```
  3x -3:08.5 preview:toggle (atom-text-editor.editor)
     -1:51.8 preview:toggle-options (atom-pane.pane)
     -1:02.5 preview:toggle (ul.list-inline.tab-bar.inset-panel)
  4x -0:47.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:31.2 core:save (atom-pane.pane)
  3x -0:17.4 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "atom-terminal-panel",
      "preview-plus"
    ]
  },
  "preview": {
    "_analyticsUserId": "11bef307-dca2-41fc-b3f7-fd92098a209c"
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v2.15.13
autocomplete-plus, v2.11.0
emmet, v2.3.7
linter, v0.12.0
preview, v0.13.7
terminal-status, v1.6.5

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Could you please provide some steps to reproduce? What is the file you are previewing, etc?

**Comment by seivan** [comment]
I get this as well. 

Only one file (notice no semicolons) 

```typescript
class Greeter<T> {
    greeting: T
    constructor(message: T) {
        this.greeting = message
    }
    greet() {
        return this.greeting
    }
}

var greeter = new Greeter<string>("Hello, world")
console.log(greeter.greet())
```
